climate:
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_1}"
    channel: 1
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_2}"
    channel: 2
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_3}"
    channel: 3
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_4}"
    channel: 4
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_5}"
    channel: 5
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_6}"
    channel: 6
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_7}"
    channel: 7
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_8}"
    channel: 8
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_9}"
    channel: 9
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_10}"
    channel: 10
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_11}"
    channel: 11
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_12}"
    channel: 12
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_13}"
    channel: 13
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_14}"
    channel: 14
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_15}"
    channel: 15
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Climate ${channel_16}"
    channel: 16
sensor:
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_1}"
    channel: 1
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_1}"
    channel: 1
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_2}"
    channel: 2
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_2}"
    channel: 2
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_3}"
    channel: 3
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_3}"
    channel: 3
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_4}"
    channel: 4
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_4}"
    channel: 4
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_5}"
    channel: 5
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_5}"
    channel: 5
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_6}"
    channel: 6
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_6}"
    channel: 6
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_7}"
    channel: 7
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_7}"
    channel: 7
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_8}"
    channel: 8
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_8}"
    channel: 8
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_9}"
    channel: 9
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_9}"
    channel: 9
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_10}"
    channel: 10
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_10}"
    channel: 10
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_11}"
    channel: 11
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_11}"
    channel: 11
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_12}"
    channel: 12
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_12}"
    channel: 12
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_13}"
    channel: 13
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_13}"
    channel: 13
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_14}"
    channel: 14
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_14}"
    channel: 14
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_15}"
    channel: 15
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_15}"
    channel: 15
    type: temperature
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Battery ${channel_16}"
    channel: 16
    type: battery
  - platform: wavinahc9000v3
    wavinahc9000v3_id: wavin
    name: "${friendly_name} Temp ${channel_16}"
    channel: 16
    type: temperature
